spring:
  application:
    name: population-service
  config:
    import: configserver:http://localhost:8888
  main:
    allow-bean-definition-overriding: true

server:
  port: 5737

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring.cloud.config.enabled: true
spring.cloud.config.import-check.enabled: false
spring.cloud.compatibility-verifier.enabled: false
